#!/bin/bash

#=======================================================================
# update
# File ID: f6345be0-abd5-11de-9791-00248cd5cf1e
# [Description]
# License: GNU General Public License version 3 or later.
#=======================================================================

(cd gpstools && {
    make remotes
    git fetch --all && git checkout master && git merge --ff-only sunbase/master
})
(cd svnutils && {
    git remote add github git@github.com:sunny256/svnutils.git
    git remote add gitorious git@gitorious.org:sunny256/svnutils.git
    git fetch --all && git checkout master && git merge --ff-only sunbase/master
    git fetch --all && git checkout master && git merge --ff-only sunbase/master
})
