#!/usr/bin/perl -w

#==============================================================================
# urlstrip
# File ID: d58ab23a-5d47-11df-a6aa-90e6ba3022ac
# Plukker ut urler fra en fil til bruk for sjekking av linker med wget --spider
#==============================================================================

use strict;

while(<>) {
	s/(http\S+?)"/print_url($1)/gies;
}

sub print_url {
    my $Url = shift;
    $Url =~ s/&amp;/&/g;
    print("$Url\n");
}
